name: Build Linux Kernel

on:
    workflow_dispatch:
      inputs:
        config:
          description: 'kernels config'
          required: false
          default: '.config'
        major_version:
          description: 'major version of the kernel 6.x.x'
          required: false
          default: '6'
        mid_version:
          description: 'middle version of the kernel x.15.x'
          required: false
          default: '15'
        minor_version:
          description: 'minor version of the kernel x.x.4'
          required: false
          default: '4'


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: install deps
              run: sudo apt-get update && sudo apt-get install build-essential wget libncurses-dev gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf -y

            - name: download kernel
              run: |
                wget https://cdn.kernel.org/pub/linux/kernel/v${{ inputs.major_version }}.x/linux-${{ inputs.major_version }}.${{ inputs.mid_version }}.${{ inputs.minor_version }}.tar.xz
                tar -xf linux-${{ inputs.major_version }}.${{ inputs.mid_version }}.${{ inputs.minor_version }}.tar.xz

            - name: copy config
              run: |
                cp ${{ github.workspace }}/${{ inputs.config }} linux-${{ inputs.major_version }}.${{ inputs.mid_version }}.${{ inputs.minor_version }}/

            - name: build kernel
              run: |
                cd linux-${{ inputs.major_version }}.${{ inputs.mid_version }}.${{ inputs.minor_version }}
                export INSTALL_DIR=${PWD}/install
                export BUILD_DIR=${PWD}/build
                export MAKE_OPTS="-j`nproc` \
                        INSTALL_PATH=${INSTALL_DIR}/boot \
                        INSTALL_MOD_PATH=${INSTALL_DIR}"
                mkdir -p ${INSTALL_DIR}
                mkdir -p ${BUILD_DIR}
                make ${MAKE_OPTS} olddefconfig
                make ${MAKE_OPTS} prepare
                make ${MAKE_OPTS} 
                make ${MAKE_OPTS} modules
                make ${MAKE_OPTS} install
                make ${MAKE_OPTS} modules_install
                make ${MAKE_OPTS} bzImage
                cp -v arch/x86/boot/bzImage ${{ github.workspace }}/vmlinuz-linux${{ inputs.major_version }}.${{ inputs.mid_version }}.${{ inputs.minor_version }}
                
            - uses: actions/upload-artifact@v4
              with:
                name: vmlinuz-linux${{ inputs.major_version }}.${{ inputs.mid_version }}.${{ inputs.minor_version }}
                path: ${{ github.workspace }}/vmlinuz-linux${{ inputs.major_version }}.${{ inputs.mid_version }}.${{ inputs.minor_version }}